# Generated by Django 2.2.1 on 2019-05-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_email',
            field=models.EmailField(blank=True, max_length=75, null=True, verbose_name='Author email'),
        ),
    ]
